### ISSUE TITLE
Please fix nodemon issues.

### ISSUE THREAD

**Issue by wtfliru** [ElDewrito/ElDewrito-MasterServer#9]
This causes a lot of issues with nodemon directly also hiawatha just... breaks.
These are all caused by newer versions that gets used, could you provide all the working legacy versions?

**Comment by Red-M** [comment]
Nodemon should be working as per their readme which states that it requires zero code changes and is just a wrapper for calling `node`. Also from reading their repository, nodemon seems to be a dev tool so why you would want this other than development on the application, I am unsure.

The git history for the node implementation (other than removing a piece of HTML from the application) has had no changes since 2015.

It may be worthwhile to try checking your environment for running the master server as this should rather simple to run.

**Comment by Red-M** [comment]
I've looked at the provided files for hiawatha, this is just a simple rproxy to the node app.

Can you post some error logs or traces as to why it seems to be breaking?
